dist: xenial   # required for Python >= 3.7

language: python

cache:
  - pip
  - apt

python:
  - "3.6"
  - "3.7"

env:
  global:
    - TRAFFIC_NOPLUGIN=""

addons:
  apt:
    packages:
      # Shapely
      - libgeos-dev
      # Cartopy
      - libproj-dev
      - proj-bin
      - proj-data

before_install:
  - python -m pip install -U pip
  - python -m pip --version

install:
  - python -m pip install --upgrade coveralls pytest-cov pytest
  - python -m pip install pyproj  # dependency for cartopy
  - python -m pip install -e .

script:
  - python -m pytest --cov shapely --cov-report term-missing

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
