[tool.black]
line-length = 80
target_version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    __pycache__
  | \.git
  | \.mypy_cache
  | \.tox
  | \.ipynb_checkpoints
  | build
  | dist
)/
'''

[tool.isort]
line_length = 80

[tool.tox]
legacy_tox_ini = """
[tox]
toxworkdir = /tmp/tox
envlist = py36, py37

[testenv]
deps =
    pytest
commands = py.test
"""
