name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 12 * * 0" # Every Sunday noon (preserve the cache folders)
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "1.3.1"

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Update full Python version
      - name: Full Python version
        run: |
          echo "PYTHON_VERSION=$(python -c "import platform; print(platform.python_version())")"
          echo "PYTHON_VERSION=$(python -c "import platform; print(platform.python_version())")" >> $GITHUB_ENV

      - name: Download extra data from private repository
        uses: actions/checkout@v3
        with:
          repository: xoolive/traffic_data
          token: ${{ secrets.PRIVATE_TOKEN }}
          persist-credentials: false
          path: ./data/traffic_data

      - name: Create LFS file list (private repository)
        working-directory: ./data/traffic_data
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        shell: bash

      - name: Restore LFS cache (private repository)
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: ./data/traffic_data/.git/lfs
          key: lfs-${{ hashFiles('./data/traffic_data/.lfs-assets-id') }}-v1

      - name: Git LFS Pull (private repository)
        working-directory: ./data/traffic_data
        run: |
          git remote set-url origin https://xoolive:${{ secrets.PRIVATE_TOKEN }}@github.com/xoolive/traffic_data.git
          git lfs pull
          unzip ENV_PostOPS_AIRAC_2111_04NOV2021_With_Airspace_Closure.zip -d airac_2111
        shell: bash

      # virtualenv cache should depends on OS, Python version and `poetry.lock` (and optionally workflow files).
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.local
            .venv
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Display Python version
        run: poetry run python -c "import sys; print(sys.version)"

      - name: Cache folder for traffic
        uses: actions/cache@v3
        id: cache-folder
        with:
          path: |
            ~/.cache/traffic/
            ~/.cache/cartes/
          key: traffic-${{ runner.os }}

      - name: Populate first cache files
        if: steps.cache-folder.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/traffic/
          cp data/navdata/earth_*.dat ~/.cache/traffic/

      - name: Ubuntu system dependencies
        run: |
          sudo apt update
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data libarchive-dev npm fonts-ubuntu
          # Weird issue with libarchive-dev
          sudo ln -s -f /usr/lib/x86_64-linux-gnu/libarchive.a /usr/lib/x86_64-linux-gnu/liblibarchive.a

      - name: npm dependencies
        run: |
          npm install vega-lite vega-cli canvas  # necessary dependency for altair-save

      - name: Install dependencies
        run: |
          poetry install -E full

          # With this version of Ubuntu, shapely is compiled with a too recent libgeos
          # https://traffic-viz.github.io/troubleshooting/installation.html
          # SHAPELY_VERSION=$(poetry run python -c "import shapely; print(shapely.__version__)")
          # poetry run pip uninstall -y shapely
          # poetry run pip install --no-binary shapely shapely==${SHAPELY_VERSION}

      - name: Build pages
        env:
          LD_LIBRARY_PATH: /usr/local/lib
          OPENSKY_USERNAME: ${{ secrets.OPENSKY_USERNAME }}
          OPENSKY_PASSWORD: ${{ secrets.OPENSKY_PASSWORD }}
          PKCS12_PASSWORD: ${{ secrets.PKCS12_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAFFIC_NOPLUGIN: ""
        run: |
          # until altair 4.3 is released
          poetry run pip install git+https://github.com/altair-viz/altair.git

          # This downloads the cache for cartes atlas
          poetry run python -c "from cartes.atlas import default, world_atlas"

          export TRAFFIC_CONFIG=$(poetry run python -c "from traffic import config_file; print(config_file)")

          sed -i "/nm_path =/ s,=$,= $PWD/data/traffic_data/airac_2111," $TRAFFIC_CONFIG
          sed -i "/pkcs12_filename =/ s,=.*$,= $PWD/data/traffic_data/CC0000007011_501_openssl.p12," $TRAFFIC_CONFIG
          sed -i "/pkcs12_password =/ s,=$,= $PKCS12_PASSWORD," $TRAFFIC_CONFIG

          # Run the documentation
          cd docs && OPENSKY_CACHE=../data/opensky_cache poetry run make html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: traffic-viz/traffic-viz.github.io
          publish_branch: master
          publish_dir: docs/_build/html
