name: docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.6
          virtualenvs-in-project: true

      - name: Display Python version
        run: poetry run python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          sudo apt install -y libgdal-dev libgeos-dev libproj-dev proj-bin proj-data libarchive-dev
          # upgrade to proj>=8.0 for Cartopy 0.20
          git clone https://github.com/OSGeo/PROJ
          cd PROJ
          git checkout 8.2.1
          mkdir build; cd build
          cmake ..
          cmake --build .
          sudo cmake --build . --target install
          cd ../..
          poetry install -E all

      - name: Build pages
        env:
          LD_LIBRARY_PATH: /usr/local/lib
        run: |
          # This line installs the theme for matplotlib
          poetry run python -c "import traffic.drawing"
          curl https://opensky-network.org/api/sensor/list -o docs/_static/sensors.json
          cd docs && poetry run make html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: traffic-viz/traffic-viz.github.io
          publish_branch: master
          publish_dir: docs/_build/html
